"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MainWin_v2.py']
DATA_FILES = ['AllocationMainWin_v2.py', 'AllocaitonDialog_v2.py', 'scales_v2.ico', 'wrench.png']
#DATA_FILES = []
OPTIONS = {'includes': ['pandas', 'PyQt5', 'datetime',
                        'AllocationMainWin_v2', 'AllocaitonDialog_v2'],
            'argv_emulation': True,
            'iconfile': 'scales_v2.ico'}
#OPTIONS = {'includes': ['pandas']}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
